### ISSUE TITLE
r151020 openJDK's patch is out of sync

### ISSUE THREAD

**Issue by xTire** [omniti-labs/omnios-build#102]
Checking for patches in patches/ (in order to apply them)
Applying patches
Running: gpatch -p1 -t -N -p0
patching file hotspot/make/solaris/makefiles/sparcWorks.make
--- Applied patch hotspot-ccsbins.patch
Running: gpatch -p1 -t -N -p0
patching file jdk/make/common/shared/Defs-solaris.gmk
patching file jdk/make/sun/awt/Makefile
Hunk #1 succeeded at 655 (offset 106 lines).
patching file jdk/make/sun/awt/mawt.gmk
patching file jdk/make/sun/font/Makefile
Hunk #1 succeeded at 205 with fuzz 1 (offset 16 lines).
patching file jdk/make/sun/jawt/Makefile
Hunk #1 succeeded at 123 (offset 5 lines).
patching file jdk/src/share/native/sun/java2d/cmm/lcms/cmsopt.c
Hunk #1 FAILED at 1535.
1 out of 1 hunk FAILED -- saving rejects to file jdk/src/share/native/sun/java2d/cmm/lcms/cmsopt.c.rej
patching file jdk/src/share/native/sun/java2d/cmm/lcms/cmstypes.c
Hunk #1 FAILED at 961.
Hunk #2 FAILED at 2946.
Hunk #3 FAILED at 3665.
Hunk #4 FAILED at 3752.
Hunk #5 FAILED at 4027.
Hunk #6 FAILED at 4519.
6 out of 6 hunks FAILED -- saving rejects to file jdk/src/share/native/sun/java2d/cmm/lcms/cmstypes.c.rej
patching file jdk/src/solaris/native/sun/awt/jawt.c
patching file jdk/src/share/native/sun/java2d/cmm/lcms/cmsxform.c
Hunk #1 FAILED at 204.
Hunk #2 FAILED at 272.
Hunk #3 FAILED at 296.
Hunk #4 FAILED at 521.
Hunk #5 FAILED at 558.
5 out of 5 hunks FAILED -- saving rejects to file jdk/src/share/native/sun/java2d/cmm/lcms/cmsxform.c.rej
--- Patch jdk-fixes.patch failed
===== Build aborted =====

**Comment by danmcd** [comment]
Try cherrypicking this patch from master:

commit a11cab22b0454d15fec1d5e36ac9c066c653dd7a
Author: Dan McDonald <danmcd@omniti.com>
Date:   Wed Jan 11 19:50:05 2017 -0500

    openjdk patches are out of sync, remove the extraneous/now-erroneous one

**Comment by xTire** [comment]
Forgive my slow network speed. 
I've patched from master manually. But build.sh seems hang at:
`cat /tmp/build_root/openjdk-1.7.0/hotspot/make/solaris/makefiles/mapfile-vers /tmp/build_root/openjdk-1.7.0/hotspot/make/solaris/makefiles/mapfile-vers-TIERED \
    | /bin/nawk '{                                         \
              if ($0 ~ "INSERT VTABLE SYMBOLS HERE") {  \
                  system ("cat vm.def");                 \
              } else {                                   \
                  print $0;                             \
              }                                          \
          }' > mapfile`

I'll try master openjdk building later.

**Comment by danmcd** [comment]
That's a known bug with the VM system. It will stop hanging the SECOND you configure a swap device.

	https://illumos.org/issues/5938

If you type "swap -l" you probably won't see anything.

The quick solution is:

     zvol create -V 1g rpool/swap
     swap -a /dev/zvol/dsk/rpool/swap

And literally your hung java build will proceed.

**Comment by xTire** [comment]
I've build it. Thank you.
