### ISSUE TITLE
New patch for OpenSSL 1.0.2 regression

### ISSUE THREAD

**Issue by moinakg** [omniti-labs/omnios-build#49]
OmniOS build gate should include this fix for an OpenSSL 1.0.2 regression that breaks pyOpenSSL and, in turn, Pkg(5) when using https publishers:
http://rt.openssl.org/Ticket/Display.html?id=3706&user=guest&pass=guest
This has recently gone into upstream.

**Comment by moinakg** [comment]
Looks like OpenSSL is prepping for a new update release, 1.0.2a with a bunch of high-impact fixes. Updating to that should handle this.

**Comment by danmcd** [comment]
We're definitely going to be updating to 1.0.2a ASAP.

Two questions:  1.) We don't have https publishers at the moment, so it's not in our test plans.  Can you test it post-1.0.2a?

2.) We are considering moving to https publishers, do you have a blog, wiki, or other experiences about using https publishers?  I'm particularly interested in the client-side of things, as I can manage the server side of things with help from my savvy OmniTI colleagues.

**Comment by moinakg** [comment]
I am currently stuck with an old OpenSolaris build but will have an OmniOS environment in the near future. However I have managed to build OpenSSL 1.0.2, Curl 7.41 and pyOpenSSL 0.13 using a whacked version of oi-userland. It all works.

Though, if the certificate of the signing authority that was used to sign the server's certificate is not present in OpenSSL's default cacerts, then it must be copied into /usr/share/pkg/cacerts. In addition a symlink, using a fingerprint hash must be created so that Curl+OpenSSL can locate it. It is described here:
http://gagravarr.org/writing/openssl-certs/others.shtml#selfsigned-openssl
Look for the command:   ln -s my_ca.crt `openssl x509 -hash -noout -in my_ca.crt`.0

Client certificates are also needed for any system that wants to access a https repo. Info on managing server and client certificates can be found here:
http://docs.oracle.com/cd/E36784_01/html/E36805/httpsrepo.html#scrolltoc

**Comment by danmcd** [comment]
Be careful mixing userland builds.  We do some things differently, INCLUDING where pkg(5) certs go, I believe.

**Comment by moinakg** [comment]
Yes, you are right. It is messy mixing userland builds, but at the moment oi-userland is the best that I have since it was modeled out of the SFW gate. Also, I had built a Solaris distro from scratch in the past (remember BeleniX ?) so kinda understand the risks.

BTW, forgot to mention, I can test the Pkg https setup with OmniOS in a VM when you get the 1.0.2a build done.

**Comment by danmcd** [comment]
I'm closing this bug since we're on 1.0.2d already.
