### ISSUE TITLE
OpenSSH issues in r151014

### ISSUE THREAD

**Issue by lotheac** [omniti-labs/omnios-build#50]
I briefly looked at OpenSSH as it is packaged for OmniOS while working on a
related problem, intending to evaluate whether we could replace SunSSH with it
in our environment. I ran into a few issues (some of which you may be aware of,
but I'll document them here nonetheless). These apply to r151014 (and possibly
earlier releases).

- network/openssh and network/openssh-server conflict with the SunSSH packages,
  obviously. However, entire has require dependencies on the SunSSH packages:
  network/ssh/ssh-key, network/ssh and service/network/ssh [0]. Perhaps this
  could be solved with a mediation like sendmail was? (I uninstalled entire as
  a workaround for testing)
- network/openssh-server does not depend on network/openssh; however, using
  SunSSH ssh-keygen the start method for the openssh service fails, because it
  attempts to generate ECDSA host keys, which SunSSH ssh-keygen cannot do
  ("unknown key type ecdsa")
- openssh-server is by default configured to use DSA, RSA, ECDSA and Ed25519
  host keys. Ed25519 keys are not generated by the shipped startup script, and
  a warning is logged.
- SunSSH cannot connect to an OmniOS box which is running OpenSSH :) (perhaps
  the default openssh sshd_config needs to be tuned wrt. KexAlgorithms)

I might be able to work on a fix for some of these in the near future, just
thought I'd document them for now.

[0]: as is documented at http://omnios.omniti.com/ticket.php/63, but the fact
that openssh was updated for 151014 suggests that it might be intended for use.
Maybe I'm missing something.

**Comment by danmcd** [comment]
We updated OpenSSH just to make sure it's as close to upstream as possible.  The problems you mention are known.  The SunSSH vs. OpenSSH problem you mention in your last bullet is because SunSSH serves up weak algorithms.  Something needs to give here, and I'm not sure what the best answer is.  My inclination is to change SunSSH to get better symmetric ciphers by default.  Most people have to "dumb down" OpenSSH servers to accept the weaker SunSSH cipher/hash pairs.

**Comment by lotheac** [comment]
On Wed, Apr 08 2015 07:40:30 -0700, Dan McDonald wrote:
> We updated OpenSSH just to make sure it's as close to upstream as
> possible. 

6.8 has been out for a couple weeks ;)

> The problems you mention are known.  The SunSSH vs. OpenSSH
> problem you mention in your last bullet is because SunSSH serves up
> weak algorithms.

I'm familiar with this, I filed this bug in illumos-gate in November:
https://www.illumos.org/issues/5283

> Something needs to give here, and I'm not sure what the best answer
> is.  My inclination is to change SunSSH to get better symmetric
> ciphers by default.

As an end user I'm inclined to the opposite, because OpenSSH has added
so many features since SunSSH :) I'm wondering if it would be feasible
for OmniOS to ship both and allow the administrator to choose (like with
the MTA mediator). I could be interested in looking into how that might
be accomplished.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by danmcd** [comment]
I'd LOVE any mediator/pkg5 help you can give.

As for 6.8, either it came out after the upgrade freeze, or I had problems compiling it such that I didn't want to hold up the release.

**Comment by lotheac** [comment]
So, there's at least two possible approaches here: using mediators, and using
mutually exclusive packages. Both approaches entail changing type=require
dependencies on ssh to require-any (sunssh, openssh). I haven't yet done any
actual work, so this all amounts to handwaving - a brain dump follows :)

With mediators, both packages would ship mediated links for their binaries,
manual pages, smf method scripts and configuration files into the expected
locations and ship the actual files elsewhere. Configuration files are what I
find problematic here; if we had /etc/sunssh and /etc/openssh with /etc/ssh
being a mediated link, it's not at all clear what would happen when upgrading
a current sunssh package with local configuration to one which introduces the
mediated link. Needs testing, I suppose. Mediators would, in theory, allow you
to install both packages and switch using 'pkg set-mediator'.

On the other hand, shipping OpenSSH and SunSSH with mutual type=exclude
dependencies could be simpler. In such a case users would not be able to
install both at the same time, so switching to the other would require package
installation. I *think* pkg could preserve existing configuration files where
a package is being replaced by another which ships the same files with
preserve attributes, but that needs testing too.

**Comment by lotheac** [comment]
Turns out Eric had already thought of the exclude dependencies when initially
creating the package, since the openssh build script already specified
excludes. The dependencies didn't get published, though, because the build
script didn't use the correct variable.

With the changes at
https://github.com/omniti-labs/omnios-build/compare/r151014...lotheac:openssh
I was able to build and install openssh, openssh-server and entire packages
that allow in-place replacement of sunssh with openssh. The syntax to achieve
this is a little cumbersome though; a blanket 'pkg install openssh
openssh-server' will just fail, one must explicitly reject all the sunssh
packages:

    % pfexec pkg install --reject pkg:/network/ssh --reject pkg:/service/network/ssh --reject pkg:/network/ssh/ssh-key -vn openssh openssh-server
                Packages to remove:         3
               Packages to install:         2
                Services to change:         1
         Estimated space available: 622.71 GB
    Estimated space to be consumed:  14.25 MB
           Create boot environment:        No
    Create backup boot environment:        No
              Rebuild boot archive:        No

    Changed packages:
    omnios
      network/ssh
        0.5.11-0.151014:20150402T175220Z -> None
      network/ssh/ssh-key
        0.5.11-0.151014:20150402T175220Z -> None
      service/network/ssh
        0.5.11-0.151014:20150402T175224Z -> None
      network/openssh
        None -> 6.7.1-0.151014:20150408T190622Z
      network/openssh-server
        None -> 6.7.1-0.151014:20150408T190651Z
    Services:
      restart_fmri:
        svc:/system/manifest-import:default

Config files in /etc/ssh are untouched by this operation if modified, and
replaced with openssh configuration if unmodified; my ssh service correctly
dropped to maintenance after doing this operation (that's exactly what I would
expect it to do; not touch my existing configuration, and try to restart).

There's still some open questions. I understand that sunssh is split into
three packages because that's how upstream illumos packages it, but I don't
know if there's much point in keeping the openssh package split (although, it
*is* possible to install network/openssh (client) and service/network/ssh
(sunssh server) at the same time with my changes, but not the other way
around). I'm also not sure whether the sunssh packages should also exclude
openssh; it seems sufficient to only do it one way.

**Comment by lotheac** [comment]
Added some more commits to my branch to address the rest of my initial concerns (modulo kexalgorithms configuration) as well as a few other low-hanging fruit in the SMF method script. Changes still at https://github.com/omniti-labs/omnios-build/compare/r151014...lotheac:openssh

Overall, I'm pretty satisfied with how this turned out. Let me know what you think.

**Comment by danmcd** [comment]
Can you put these into master?  I'm spinning up bloody to r151015. I'd prefer to get it working there, and then backport.

**Comment by lotheac** [comment]
On Wed, Apr 08 2015 13:31:41 -0700, Dan McDonald wrote:
> Can you put these into master?  I'm spinning up bloody to r151015. I'd
> prefer to get it working there, and then backport.

Yeah, sure, sorry about that - I'm working in a zone on 151014 so that
was my starting point. Cherry-picked to
https://github.com/omniti-labs/omnios-build/compare/master...lotheac:openssh_master

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by oetiker** [comment]
any progress on this? would love to have a "current" openssh on omni ... not only because of the ciphers ...

**Comment by lotheac** [comment]
On Fri, May 22 2015 17:35:52 -0700, Tobias Oetiker wrote:
> any progress on this? would love to have a "current" openssh on omni
> ... not only because of the ciphers ... 

Working for me, but Dan'll know better about the integration status :)

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by lotheac** [comment]
@danmcd - any progress on getting this integrated?

**Comment by danmcd** [comment]
1.) Where's the pull request?

2.) I'm in/out/vacation until late next week.  Pardon any latency.

**Comment by lotheac** [comment]
On Wed, Jun 10 2015 06:07:51 -0700, Dan McDonald wrote:
> 1.) Where's the pull request?

Right, I guess there isn't one (just a reference to my branch in this
issue). I'll make an actual PR.

-- 
Lauri Tirkkonen | lotheac @ IRCnet
