### ISSUE TITLE
RUN_DEPENDS_IPS packages with regex special characters in their names can break package build

### ISSUE THREAD

**Issue by lotheac** [omniti-labs/omnios-build#51]
Ran into this while looking into #50.

    pkgmogrify: File /tmp/build_lotheac/network_openssh.deps.mog, line 6: transform (<transform depend fmri=(.+/)?system/library/g++-4-runtime -> set fmri system/library/g++-4-runtime@4.7.2>) has regexp error (multiple repeat) in matching clause

This is caused by my pkgdepend changes; the build script in question
explicitly specifies the system/library/g++-4-runtime dependency, and since it
is thrown into the transform clause as-is, the + signs are misinterpreted.

Not sure what to do with this yet.

**Comment by danmcd** [comment]
Please inspect the https://github.com/omniti-labs/pkg5/ code and make sure I didn't mismerge anything from your pkgdepend.

**Comment by lotheac** [comment]
On Wed, Apr 08 2015 13:10:43 -0700, Dan McDonald wrote:
> Please inspect the https://github.com/omniti-labs/pkg5/ code and make
> sure I didn't mismerge anything from your pkgdepend.

I'll rephrase: my changes that run pkgdepend in omnios-build, not
changes in pkgpdepend.

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by lotheac** [comment]
This is quite annoying to fix correctly because we are a shell script that outputs to a mog file which is matched against python regular expressions.

This fix probably doesn't work for every possible package name (because among other things, we're passing the dependency package name to grep as well) and isn't that pretty otherwise either, but: https://github.com/omniti-labs/omnios-build/compare/master...niksula:escape_depname

**Comment by danmcd** [comment]
Merged
