### ISSUE TITLE
How about a newer version of gnu make?

### ISSUE THREAD

**Issue by andy-js** [omniti-labs/omnios-build#55]
The current version seems to be 3.82 which is prehistoric.  Version 4.1 has some nice fixes that make life easier when building on multiple cores.

**Comment by andy-js** [comment]
I'm running into this bug with the current version of make: http://savannah.gnu.org/bugs/?33134
How about an update?

**Comment by danmcd** [comment]
> On Jun 21, 2015, at 4:42 PM, Andrew Stormont <notifications@github.com> wrote:
> 
> I'm running into this bug with the current version of make: http://savannah.gnu.org/bugs/?33134
> How about an update?

I *thought* I had problems updating (sterotypical gnu interface breakage), but I don't see any notes on it, so it may be a simple upgrade to build.sh.

I also see that there was an attempt at 4.0, but it was done prior to my arrival at OmniTI.  Perhaps someone else has some historical perspective on this?

Sorry,
Dan

**Comment by ptribble** [comment]
I second an update to 4.1. Another issue, which has led me to avoid 3.82 like the plague, is https://savannah.gnu.org/bugs/?33034

**Comment by danmcd** [comment]
I believe there are a series of sweater-pulls that result from trying to update gmake to 4.1.  Off the top of my head:

	- glib2 would need an update

	- glib2 updates cause much of the world to break around it, including some things in either pkg(5) or illumos itself which are stuck.

And I think I'm missing other threads in the unravelling sweater.

I just locally updated a ton of things for '016.  Assuming that bootstraps okay, they'll show up in omnios-build:master.  After that, I may give gmake another try.

**Comment by danmcd** [comment]
Surprisingly, gmake 4.1 built very smoothly.  I'm still in my OOod build cycles for the tons of other things.  If all goes well (and that's a big IF), I might be able to have 4.1 land in r151016.

Anyone on this thread should update to the next bloody I announce.  Watch the omnios-discuss list, please.

**Comment by danmcd** [comment]
In both bloody and r151016.
