### ISSUE TITLE
OmniOS ships a junk libpython2.6_db

### ISSUE THREAD

**Issue by richlowe** [omniti-labs/omnios-build#83]
You build libpython2.6_db like this (from `Python26-20-py_db.patch`)

```make
SHLIB_FLAGS = -shared -fpic -M $(srcdir)/py_db/mapfile-vers

libpython2.6_db.so.1.0:	$(srcdir)/py_db/libpython26_db.c
	$(CC) -o $@ $(CFLAGS) $(CPPFLAGS) $(SHLIB_FLAGS) $<
```

This pass `-M` to `$(CC)` expecting to specify a mapfile, as you would with Studio.  Unfortunately, -M means something else to GCC.  The output of dependencies for make (in a manner similar to our state keeping).

This means that the python debugger support shipped by OmniOS is trash and pstack and mdb can't show python frames.

`file /usr/lib/libpython2.6_db.so.1.0` will show what I mean, as will:

`curl omnios.omniti.com/omnios/release/file/0/15fb42db15bee294189caad3cdf9c45ef31a803d | gzip -dc`  Which fetches that path from the latest release.  It should be an ELF shared object.  Clearly it isn't.

You can fix it by

```diff
  
  $(LIBRARY_OBJS) $(MODOBJS) Modules/python.o: $(PYTHON_HEADERS)
  
-+SHLIB_FLAGS = -shared -fpic -M $(srcdir)/py_db/mapfile-vers
++SHLIB_FLAGS = -shared -fpic -Wl,-M,$(srcdir)/py_db/mapfile-vers
 +
 +libpython2.6_db.so.1.0:	$(srcdir)/py_db/libpython26_db.c
 +	$(CC) -o $@ $(CFLAGS) $(CPPFLAGS) $(SHLIB_FLAGS) $<
```

**Comment by danmcd** [comment]
Okay!  Please confirm:

`
bloody(build/python26)[0]% git diff
diff --git a/build/python26/patches/Python26-20-py_db.patch b/build/python26/patches/Python26-20-py_db.patch
index 2bf056f..7b469fa 100644
--- a/build/python26/patches/Python26-20-py_db.patch
+++ b/build/python26/patches/Python26-20-py_db.patch
@@ -14,7 +14,7 @@ diff -ruN Python-2.6.7-orig/Makefile.pre.in Python-2.6.7/Makefile.pre.in
  
  $(LIBRARY_OBJS) $(MODOBJS) Modules/python.o: $(PYTHON_HEADERS)
  
-+SHLIB_FLAGS = -shared -fpic -M $(srcdir)/py_db/mapfile-vers
++SHLIB_FLAGS = -shared -fpic -Wl,-M,$(srcdir)/py_db/mapfile-vers
 +
 +libpython2.6_db.so.1.0:       $(srcdir)/py_db/libpython26_db.c
 +      $(CC) -o $@ $(CFLAGS) $(CPPFLAGS) $(SHLIB_FLAGS) $<
bloody(build/python26)[0]% 
`

**Comment by danmcd** [comment]
Committed.
